#pragma once

#define PUMP_START_SENSOR_VALUE 700 // 0 wet
#define PUMP_STOP_SENSOR_VALUE 800 // 1023 dry
#define MAX_PUMP_DURATION_IN_SEC 900
#define PUMP_COOL_DOWN_IN_SEC 60

#define MAX_SENSOR_SAMPLES 16
#define SENSOR_PIN A0
#define SENSOR_VCC_PIN 11
#define RELAY_PIN 12
#define LED_PIN 13

#define RC433_MIN_SEND_INTERVAL_IN_SEC 1
#define RC433_MAX_SEND_INTERVAL_IN_SEC 10

#define RC433_POWER_PIN 8
#define RC433_DATA_PIN 9
